In [1]:
import torch
import numpy as np
from torch.autograd import Variable

In [24]:
# Создайте случайный FloatTensor размера 3x4x5
x = torch.FloatTensor([[[1, 1, 1, 1, 1], [2, 2, 2, 2, 2], [3, 3, 3, 3, 3], [4, 4, 4, 4, 4]],
                       [[1, 1, 1, 1, 1], [2, 2, 2, 2, 2], [3, 3, 3, 3, 3], [4, 4, 4, 4, 4]],
                       [[1, 1, 1, 1, 1], [2, 2, 2, 2, 2], [3, 3, 3, 3, 3], [4, 4, 4, 4, 4]]])
x

tensor([[[1., 1., 1., 1., 1.],
         [2., 2., 2., 2., 2.],
         [3., 3., 3., 3., 3.],
         [4., 4., 4., 4., 4.]],

        [[1., 1., 1., 1., 1.],
         [2., 2., 2., 2., 2.],
         [3., 3., 3., 3., 3.],
         [4., 4., 4., 4., 4.]],

        [[1., 1., 1., 1., 1.],
         [2., 2., 2., 2., 2.],
         [3., 3., 3., 3., 3.],
         [4., 4., 4., 4., 4.]]])

In [25]:
# Выведите его форму (shape)
x.shape

torch.Size([3, 4, 5])

In [26]:
# Приведите его к форме 6 X 10
x = x.view(-1, 10)

In [27]:
x

tensor([[1., 1., 1., 1., 1., 2., 2., 2., 2., 2.],
        [3., 3., 3., 3., 3., 4., 4., 4., 4., 4.],
        [1., 1., 1., 1., 1., 2., 2., 2., 2., 2.],
        [3., 3., 3., 3., 3., 4., 4., 4., 4., 4.],
        [1., 1., 1., 1., 1., 2., 2., 2., 2., 2.],
        [3., 3., 3., 3., 3., 4., 4., 4., 4., 4.]])

In [35]:
# Умножьте его на вектор [1, 4, 2, 2, 1] поэлементно
x * torch.FloatTensor([1, 4, 2, 2, 1, 1, 4, 2, 2, 1])

tensor([[ 1.,  4.,  2.,  2.,  1.,  2.,  8.,  4.,  4.,  2.],
        [ 3., 12.,  6.,  6.,  3.,  4., 16.,  8.,  8.,  4.],
        [ 1.,  4.,  2.,  2.,  1.,  2.,  8.,  4.,  4.,  2.],
        [ 3., 12.,  6.,  6.,  3.,  4., 16.,  8.,  8.,  4.],
        [ 1.,  4.,  2.,  2.,  1.,  2.,  8.,  4.,  4.,  2.],
        [ 3., 12.,  6.,  6.,  3.,  4., 16.,  8.,  8.,  4.]])

In [39]:
# Умножьте тензор матрично на себя, чтобы результат был размерности 6x6
torch.matmul(x, x.T)

tensor([[ 25.,  55.,  25.,  55.,  25.,  55.],
        [ 55., 125.,  55., 125.,  55., 125.],
        [ 25.,  55.,  25.,  55.,  25.,  55.],
        [ 55., 125.,  55., 125.,  55., 125.],
        [ 25.,  55.,  25.,  55.,  25.,  55.],
        [ 55., 125.,  55., 125.,  55., 125.]])

In [51]:
# Посчитайте производную функции y = x**3 + z - 75t в точке (1, 0.5, 2)
x = Variable(torch.FloatTensor([1, 0.5, 2]), requires_grad = True)
y = x**3 + x - 75*x
y.backward(x)
print(x.grad)

tensor([ -71.0000,  -36.6250, -124.0000])


In [56]:
# Создайте единичный тензор размера 5x6
y = torch.IntTensor(np.ones([5, 6]))
y

tensor([[1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1]], dtype=torch.int32)

In [63]:
# Переведите его в формат numpy
y.numpy()

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]], dtype=int32)

In [71]:
# Давайте теперь пооптимизируем: возьмите функцию y = x**w1 - 2 * x**2 + 5
# Посчитайте 
linear = nn.Linear(3, 3)
y = x ** linear.weight - 2 * x ** 2 + 5
criterion = nn.MSELoss()
optimizer = torch.optim.SGD(linear.parameters(), lr=0.01)
optimizer.zero_grad()
pred = linear(y)
loss = criterion(pred, y)
print('loss: ', loss.item())


loss:  27.806800842285156
